[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "kreditomat-frontend"
type = "web"

[services.kreditomat-frontend]
port = 3000

# Environment variables will be set in Railway dashboard